services:
  - type: web
    name: fastapi-app
    env: python
    region: india  # or any other region
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 80

